name: pinout check

on: [push]

jobs:
  pinout:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Checkout pcb-versions
        uses: actions/checkout@v4
        with:
          repository: RaccoonLabHardware/pcb-versions
          token: ${{ secrets.ACCESS_TOKEN }}
          path: pcb-versions

      - name: Test pinout
        run: |
          ./pcb-versions/scripts/test_ioc.py pcb-versions/configs/required_pinout_v3.yml *.ioc
